### ISSUE TITLE
Make all numbers right aligned in lists

### ISSUE THREAD

**Issue by tnevolin** [Xilmi/OpenXcom#21]
Make all numbers right aligned in lists.
Create additional column for measurement unit whenever it is present, usually %. To keep rest of the numbers right aligned.
Modify dot connecting routine to make sure they are extended to the right an left for each column but not outside of the list.

**Comment by tnevolin** [comment]
Modified lists:
* Craft inventory
* Research
* Monthly costs
* Purchase
* Sell
* Stores
* Transfer
* Debriefing
* Funding

Didn't bother with smaller list and OCXE based ones (mods, options, etc.). Let me know if you want to change something else. It is not a problem, just tedious to track them all.

**Comment by Xilmi** [comment]
tnevolin has submitted this change and it was merged.
