### ISSUE TITLE
Pressing 'Alt' to show unit facing arrow in battlescape only works sometimes

### ISSUE THREAD

**Issue by zrrr111** [Xilmi/OpenXcom#45]
Hi. It seems recent changes and merge issues with `src/Battlescape/Map.cpp` broke unit facing arrow feature.

In both latest OXCE and BOXCE pressing 'alt' in battlescape should make an arrow icon appear above any unit. In BOXCE 9.1.5 it only works sometimes, and breaks or fixes itself after several battlescape reloads (with quickload, for example)

Possible cause is use of uninitialized `_isCtrlPressed` object field in [Map.cpp#L711](https://github.com/Xilmi/OpenXcom/blob/b35c4d827f6f1c312f4c1b1b8f70784052d42ad0/src/Battlescape/Map.cpp#L711), which was added with merge from upstream, removed, and later readded with another merge. Maybe adding initializer in constructor or setting it like upstream does [Map.cpp#L734](https://github.com/MeridianOXC/OpenXcom/blob/ee72cc2bb48d5b4c49ed52dd58ee9d940eafa06d/src/Battlescape/Map.cpp#L734) can fix it.

**Comment by Xilmi** [comment]
I used the suggested change and with it couldn't reproduce the issue.
Not sure if it's definitely fixed or I'm just lacking the proper way to reproduce it though.

**Comment by zrrr111** [comment]
Works for me and other people, who complained before, so I believe this is fixed in 9.2.0.
